### ISSUE TITLE
Generated project for Talon project type has error

### ISSUE THREAD

**Issue by MajikalExplosions** [wpilibsuite/robot-characterization#38]
The project that is generated for the Talon project type has an error in Robot.java.  `robotInit()` creates local `leftMaster` and `rightMaster` objects instead of using the global variables with the same name, which causes a NullPointerException in `autonomousPeriodic()`.

**Comment by Oblarg** [comment]
This was fixed shortly after the switch to frc-characterization from robotpy-characterization.  Make sure you're using the recent version.
